#!/usr/bin/env bun
/**
 * Render Companies/companies.md from the registry — deduped, grouped by how
 * targetable each company is. The raw dump is preserved as companies.raw.md.bak.
 *
 *   bun run scripts/organize.ts
 */
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
const DIR = join(dirname(fileURLToPath(import.meta.url)), "..", "Companies");

interface E { name:string; url:string; domain:string; ats:string|null; atsToken:string|null;
  atsSupported:boolean; jobsTotal:number|null; jobsEligible:number|null; resolveAttemptedAt?:string|null }

const doc = Bun.YAML.parse(await Bun.file(join(DIR,"registry.yaml")).text()) as {companies:E[]};
const all = doc.companies;
const ready   = all.filter(e => e.atsSupported).sort((a,b)=>(b.jobsTotal??0)-(a.jobsTotal??0));
const probed  = all.filter(e => !e.atsSupported && e.resolveAttemptedAt);
const pending = all.filter(e => !e.atsSupported && !e.resolveAttemptedAt);

const rows = (list:E[]) => list.map(e =>
  `| ${e.name} | \`${e.ats}:${e.atsToken}\` | ${e.jobsTotal ?? "-"} | [careers](${e.url}) |`);

const md = [
  "# Target companies",
  "",
  `> Generated by \`bun run scripts/organize.ts\` from \`registry.yaml\`.`,
  `> ${all.length} unique companies. Raw dump preserved at \`companies.raw.md.bak\`.`,
  `> Add new careers URLs to any \`.md\` here and run \`bun run scripts/companies.ts\` to ingest,`,
  `> then \`bun run scripts/resolve.ts --limit 100\` to find their job boards.`,
  "",
  `## Ready to target (${ready.length})`,
  "",
  "Job board resolved and readable by an adapter. Scan with `bun run src/cli.ts scan <ats>:<token>`.",
  "",
  "| company | board | open roles | link |",
  "|---|---|---:|---|",
  ...rows(ready),
  "",
  `## Probed, no board found (${probed.length})`,
  "",
  "Tried every supported ATS with candidate tokens and none answered — these likely use",
  "Workday, iCIMS, Taleo or a bespoke page. They need a Firecrawl/Playwright ingest tier.",
  "",
  ...probed.map(e => `- ${e.name} — [careers](${e.url})`),
  "",
  `## Not yet probed (${pending.length})`,
  "",
  "Run `bun run scripts/resolve.ts --limit 100` repeatedly to work through these.",
  "",
  ...pending.map(e => `- ${e.name} — [careers](${e.url})`),
  "",
].join("\n");

await Bun.write(join(DIR,"companies.md"), md);
console.log(`organized: ${ready.length} ready | ${probed.length} probed-no-board | ${pending.length} pending`);
console.log(`total open roles across ready boards: ${ready.reduce((a,e)=>a+(e.jobsTotal??0),0)}`);
